import { useState, useMemo, useCallback } from "react";
import {
  templates,
  categories,
  type GitignoreTemplate,
  type Category,
} from "@/data/gitignore-templates";
import { Header } from "@/components/Header";
import { CategoryFilter } from "@/components/CategoryFilter";
import { LanguageGrid } from "@/components/LanguageGrid";
import { OutputPanel } from "@/components/OutputPanel";
import { FloatingOrbs } from "@/components/FloatingOrbs";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./index.css";
import { Button } from "./components/ui/button";

export function App() {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [activeCategory, setActiveCategory] = useState<Category | "All">("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [showOutput, setShowOutput] = useState(false);

  const filteredTemplates = useMemo(() => {
    return templates.filter((t) => {
      const matchesCategory =
        activeCategory === "All" || t.category === activeCategory;
      const matchesSearch =
        !searchQuery ||
        t.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        t.description.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    });
  }, [activeCategory, searchQuery]);

  const selectedTemplates = useMemo(() => {
    return templates.filter((t) => selected.has(t.id));
  }, [selected]);

  const generatedContent = useMemo(() => {
    if (selectedTemplates.length === 0) return "";

    const sections = selectedTemplates.map((t) => {
      const header = `# ========================================`;
      const title = `# ${t.icon} ${t.name}`;
      const footer = `# ========================================`;
      const patterns = t.patterns.join("\n");
      return `${header}\n${title}\n${footer}\n${patterns}`;
    });

    const banner = [
      "# ╔══════════════════════════════════════════╗",
      "# ║      Generated by .gitignore Generator   ║",
      "# ╚══════════════════════════════════════════╝",
      "",
    ].join("\n");

    return banner + "\n" + sections.join("\n\n");
  }, [selectedTemplates]);

  const toggleTemplate = useCallback((id: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }, []);

  const selectAll = useCallback(
    (categoryTemplates: GitignoreTemplate[]) => {
      setSelected((prev) => {
        const next = new Set(prev);
        const allSelected = categoryTemplates.every((t) => next.has(t.id));
        if (allSelected) {
          categoryTemplates.forEach((t) => next.delete(t.id));
        } else {
          categoryTemplates.forEach((t) => next.add(t.id));
        }
        return next;
      });
    },
    []
  );

  const clearAll = useCallback(() => {
    setSelected(new Set());
  }, []);

  return (
    <TooltipProvider delayDuration={200}>
      <div className="relative min-h-screen overflow-hidden">
        {/* Background effects */}
        <FloatingOrbs />
        <div className="grid-bg radial-mask fixed inset-0 animate-grid-pulse pointer-events-none" />

        {/* Main content */}
        <div className="relative z-10">
          <Header
            selectedCount={selected.size}
            onClearAll={clearAll}
            showOutput={showOutput}
            onToggleOutput={() => setShowOutput(!showOutput)}
          />

          <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
            <div className="w-full m-4 flex justify-between">
              <a href="https://digitalheroesco.com/"><Button variant={"outline"} className="cursor-pointer">Built for digital heroes</Button></a>
              <div className="flex flex-col">
                  <h2 className="text-accent-foreground text-sm font-semibold">Tanishq Singh Bisht</h2>
                  <h4 className="text-accent-foreground text-xs">Email : tanishq1172005@gmail.com</h4>
              </div>
              
            </div>
            
            {/* Search bar */}
            <div className="mt-8 mb-6 max-w-xl mx-auto animate-fade-up" style={{ animationDelay: "0.2s", opacity: 0 }}>
              
              <div className="relative group">
                <div className="absolute inset-0 bg-linear-to-r from-[oklch(0.75_0.18_270/0.2)] via-[oklch(0.65_0.2_300/0.2)] to-[oklch(0.75_0.18_270/0.2)] rounded-xl blur-xl opacity-0 group-focus-within:opacity-100 transition-opacity duration-500" />
                <div className="relative">
                  <svg
                    className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground transition-colors group-focus-within:text-primary"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                    />
                  </svg>
                  <input
                    id="search-input"
                    type="text"
                    placeholder="Search languages, frameworks, tools..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full pl-12 pr-4 py-3.5 bg-card/60 backdrop-blur-sm border border-border rounded-xl text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary/50 transition-all duration-300"
                  />
                  {searchQuery && (
                    <button
                      onClick={() => setSearchQuery("")}
                      className="absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                    >
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  )}
                </div>
              </div>
            </div>

            {/* Category filter */}
            <CategoryFilter
              categories={categories}
              activeCategory={activeCategory}
              onCategoryChange={setActiveCategory}
              templateCounts={categories.reduce(
                (acc, cat) => {
                  acc[cat.name] = templates.filter(
                    (t) => t.category === cat.name
                  ).length;
                  return acc;
                },
                { All: templates.length } as Record<string, number>
              )}
            />

            {/* Language grid */}
            <LanguageGrid
              templates={filteredTemplates}
              selected={selected}
              onToggle={toggleTemplate}
              onSelectAll={selectAll}
              activeCategory={activeCategory}
            />
          </main>

          {/* Output panel */}
          <OutputPanel
            content={generatedContent}
            selectedTemplates={selectedTemplates}
            isOpen={showOutput || selected.size > 0}
            onClose={() => setShowOutput(false)}
            onRemove={(id) => toggleTemplate(id)}
          />
        </div>
      </div>
    </TooltipProvider>
  );
}

export default App;
